steps:
  # 1. Budowanie obrazu Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/keepgoals-repo/backend:$COMMIT_SHA', '.']

  # 2. Wypchnięcie obrazu do Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/keepgoals-repo/backend:$COMMIT_SHA']

  # 3. Wdrożenie zaktualizowanego obrazu do Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'keepgoals-backend'
      - '--image'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/keepgoals-repo/backend:$COMMIT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,FIREBASE_CREDENTIALS_PATH=FIREBASE_CREDENTIALS_PATH:latest'

images:
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/keepgoals-repo/backend:$COMMIT_SHA'
